global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node-app'
    static_configs:
      - targets: ['172.31.4.210:3000']
  - job_name: 'node-exporter-app'
    static_configs:
      - targets: ['172.31.4.210:9100']
  - job_name: 'node-exporter-monitor'
    static_configs:
      - targets: ['172.31.2.217:9100']