global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node-app'
    static_configs:
      - targets: ['${{ secrets.NODE_HOST_IP }}:3000']
  - job_name: 'node-exporter-app'
    static_configs:
      - targets: ['${{ secrets.NODE_HOST_IP }}:9100']
  - job_name: 'node-exporter-monitor'
    static_configs:
      - targets: ['${{ secrets.MONITOR_HOST_IP }}:9100']