global:
  scrape_interval: 15s

scrape_configs:
- job_name: 'app'
  static_configs:
    - targets: ['NODE_HOST:3000']
- job_name: 'node-exporter-app'
  static_configs:
    - targets: ['NODE_HOST:9100']
- job_name: 'node-exporter-monitor'
  static_configs:
    - targets: ['MONITOR_HOST:9100']
