name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./node-app
          file: ./node-app/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/node-app:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/node-app:${{ github.sha }}

  deploy-to-ec2:
    needs: build-and-push-image
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Node EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.NODE_EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/node-app:latest
            docker stop node-app || true
            docker rm node-app || true
            docker run -d \
              --name node-app \
              --restart unless-stopped \
              -p 3000:3000 \
              ${{ secrets.DOCKERHUB_USERNAME }}/node-app:latest

      - name: Checkout monitoring code
        uses: actions/checkout@v3
        with:
          path: monitoring-project

      - name: Ensure monitoring folder exists on Monitoring EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.MONITOR_EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: mkdir -p ~/monitoring

      - name: Copy monitoring folder to Monitoring EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.MONITOR_EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "monitoring-project/monitoring"
          target: "~/monitoring"
          strip_components: 2  #FIXED: Removes monitoring-project/monitoring folder nesting --- new learning

      - name: Deploy to Monitoring EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.MONITOR_EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/monitoring
            docker-compose down || true
            docker-compose up -d